name: Node CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - soon-to-be-born

jobs:

  build:
  
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, mac-ATTACK]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
